export const SHOW_ERROR= "SHOW_ERROR";
export const DISMISS_ERROR= "DISMISS_ERROR";
export const MENU_OPENED = "MENU_OPENED";
export const MENU_CLOSED = "MENU_CLOSED";
export const CHARACTERS_LOADING = "CHARACTERS_LOADING";
export const CHARACTERS_LOADED = "CHARACTERS_LOADED";
export const CHARACTERS_STOPPED_LOADING = "CHARACTERS_STOPPED_LOADING";
